### ISSUE TITLE
BGC could not be detected---_No BGCs were detected in the metagenome_

### ISSUE THREAD

**Issue by XT920** [danielchang2002/TaxiBGC_2022#3]
Total time:             82.529 seconds.

Downloading http://cmprod1.cibio.unitn.it/biobakery3/metaphlan_databases/mpa_latest
Downloading file of size: 0.00 MB
0.01 MB 31507.69 %  55.07 MB/sec  0 min -0 sec         
Downloading MetaPhlAn database
Please note due to the size this might take a few minutes

Downloading http://cmprod1.cibio.unitn.it/biobakery3/metaphlan_databases/mpa_v31_CHOCOPhlAn_201901.tar
Downloading file of size: 407.85 MB
407.85 MB 100.00 %   0.47 MB/sec  0 min  0 sec         
Downloading http://cmprod1.cibio.unitn.it/biobakery3/metaphlan_databases/mpa_v31_CHOCOPhlAn_201901.md5
Downloading file of size: 0.00 MB
0.01 MB 12800.00 %  56.11 MB/sec  0 min -0 sec         

Decompressing /home/map/anaconda3/envs/taxibgc_env/lib/python3.8/site-packages/metaphlan/metaphlan_databases/mpa_v31_CHOCOPhlAn_201901.fna.bz2 into /home/map/anaconda3/envs/taxibgc_env/lib/python3.8/site-packages/metaphlan/metaphlan_databases/mpa_v31_CHOCOPhlAn_201901.fna

Building Bowtie2 indexes
Removing uncompress database /home/map/anaconda3/envs/taxibgc_env/lib/python3.8/site-packages/metaphlan/metaphlan_databases/mpa_v31_CHOCOPhlAn_201901.fna

Download complete
WARNING: The metagenome profile contains clades that represent multiple species merged into a single representant.
An additional column listing the merged species is added to the MetaPhlAn output.
_No BGCs were detected in the metagenome_

**Comment by danielchang2002** [comment]
Hi, it's totally normal for no BGCs to be detected in the metagenome. This is most likely correct, especially if the coverage stats file and metaphlan output file look normal (do they?).

**Comment by XT33KAKA** [comment]
These are the contents of two output files, and the final output file is empty, I do not know whether such output results are normal, and secondly, does the final output result contain the sequence information of BGC, like the result of antismash, can you see the information of the ORF site of BGC? Or is it just the BGC's Fen Fen Du forecast? Thank you.


L1.fastq_covstats_taxibgc2022.txt
#ID	Avg_fold	Length	Ref_GC	Covered_percent	Covered_bases	Plus_reads	Minus_reads	Read_GC	Median_fold	Std_Dev
BGC0000001_orfP_1	0.0000	1083	0.7138	0.0000	0	0	0	0.0000	0	0.00
BGC0000001_NULL_2	0.0000	627	0.6794	0.0000	0	0	0	0.0000	0	0.00
BGC0000001_abyR_3	0.0000	747	0.6961	0.0000	0	0	0	0.0000	0	0.00
BGC0000001_abyX_4	0.0000	1191	0.6986	0.0000	0	0	0	0.0000	0	0.00
BGC0000001_abyH_5	0.0000	2670	0.7502	0.0000	0	0	0	0.0000	0	0.00
BGC0000001_abyI_6	0.0000	759	0.7101	0.0000	0	0	0	0.0000	0	0.00
BGC0000001_abyK_7	0.0000	1860	0.7161	0.0000	0	0	0	0.0000	0	0.00
BGC0000001_abyA1_8	0.0000	1026	0.7212	0.0000	0	0	0	0.0000	0	0.00
BGC0000001_abyA2_9	0.0000	1869	0.7309	0.0000	0	0	0	0.0000	0	0.00
BGC0000001_abyA3_10	0.0000	237	0.7131	0.0000	0	0	0	0.0000	0	0.00
BGC0000001_abyA4_11	0.0000	756	0.7368	0.0000	0	0	0	0.0000	0	0.00
BGC0000001_abyA5_12	0.0000	1068	0.7275	0.0000	0	0	0	0.0000	0	0.00
BGC0000001_abyB1_13	0.0000	17346	0.7441	0.0000	0	0	0	0.0000	0	0.00
BGC0000001_abyB2_14	0.0000	10938	0.7605	0.0000	0	0	0	0.0000	0	0.00
BGC0000001_abyB3_15	0.0000	2979	0.7543	0.0000	0	0	0	0.0000	0	0.00
BGC0000001_abyC_16	0.0000	693	0.7215	0.0000	0	0	0	0.0000	0	0.00
BGC0000001_abyD_17	0.0000	1428	0.7164	0.0000	0	0	0	0.0000	0	0.00
BGC0000001_abyE_18	0.0000	1008	0.7341	0.0000	0	0	0	0.0000	0	0.00
BGC0000001_abyF1_19	0.0000	1617	0.7081	0.0000	0	0	0	0.0000	0	0.00
BGC0000001_abyF2_20	0.0000	936	0.7382	0.0000	0	0	0	0.0000	0	0.00
BGC0000001_abyF3_21	0.0000	852	0.7465	0.0000	0	0	0	0.0000	0	0.00
BGC0000001_abyF4_22	0.0000	1620	0.7426	0.0000	0	0	0	0.0000	0	0.00
BGC0000001_abyV_23	0.0000	1188	0.7256	0.0000	0	0	0	0.0000	0	0.00
BGC0000001_abyW_24	0.0000	252	0.7381	0.0000	0	0	0	0.0000	0	0.00
**Etc.**

&

L1.fastq_BGC_metsp.txt
s__Lactobacillus_phage_Sha1	10239|||28883|10699||947981	0.744736534407015	
s__Ateline_gammaherpesvirus_3	10239|||548681|10292|10379|85618	0.7419191692604009	
s__Streptococcus_sp_HMSC069D09

**Comment by XT920** [comment]
The result indicates that no BGC was detected, which is the content of the two output files, and the final output file is empty, I don't know whether the output result is normal. Secondly, does the final output result contain the sequence information of BGC, just like the result of antismash? Can the second tool see the information of the ORF site of BGC? Or is it just a prediction of BGC abundance? Thank you very much!


L1.fastq_covstats_taxibgc2022.txt
#ID Avg_fold Length Ref_GC Covered_percent Covered_bases Plus_reads Minus_reads Read_GC Median_fold Std_Dev
BGC0000001_orfP_1 0.0000 1083 0.7138 0.0000 0 0 0 0.0000 0 0.00
BGC0000001_NULL_2 0.0000 627 0.6794 0.0000 0 0 0 0.0000 0 0.00
BGC0000001_abyR_3 0.0000 747 0.6961 0.0000 0 0 0 0.0000 0 0.00
BGC0000001_abyX_4 0.0000 1191 0.6986 0.0000 0 0 0 0.0000 0 0.00
BGC0000001_abyH_5 0.0000 2670 0.7502 0.0000 0 0 0 0.0000 0 0.00
BGC0000001_abyI_6 0.0000 759 0.7101 0.0000 0 0 0 0.0000 0 0.00
BGC0000001_abyK_7 0.0000 1860 0.7161 0.0000 0 0 0 0.0000 0 0.00
BGC0000001_abyA1_8 0.0000 1026 0.7212 0.0000 0 0 0 0.0000 0 0.00
BGC0000001_abyA2_9 0.0000 1869 0.7309 0.0000 0 0 0 0.0000 0 0.00
BGC0000001_abyA3_10 0.0000 237 0.7131 0.0000 0 0 0 0.0000 0 0.00
BGC0000001_abyA4_11 0.0000 756 0.7368 0.0000 0 0 0 0.0000 0 0.00
BGC0000001_abyA5_12 0.0000 1068 0.7275 0.0000 0 0 0 0.0000 0 0.00
BGC0000001_abyB1_13 0.0000 17346 0.7441 0.0000 0 0 0 0.0000 0 0.00
BGC0000001_abyB2_14 0.0000 10938 0.7605 0.0000 0 0 0 0.0000 0 0.00
BGC0000001_abyB3_15 0.0000 2979 0.7543 0.0000 0 0 0 0.0000 0 0.00
BGC0000001_abyC_16 0.0000 693 0.7215 0.0000 0 0 0 0.0000 0 0.00
BGC0000001_abyD_17 0.0000 1428 0.7164 0.0000 0 0 0 0.0000 0 0.00
BGC0000001_abyE_18 0.0000 1008 0.7341 0.0000 0 0 0 0.0000 0 0.00
BGC0000001_abyF1_19 0.0000 1617 0.7081 0.0000 0 0 0 0.0000 0 0.00
BGC0000001_abyF2_20 0.0000 936 0.7382 0.0000 0 0 0 0.0000 0 0.00
BGC0000001_abyF3_21 0.0000 852 0.7465 0.0000 0 0 0 0.0000 0 0.00
BGC0000001_abyF4_22 0.0000 1620 0.7426 0.0000 0 0 0 0.0000 0 0.00
BGC0000001_abyV_23 0.0000 1188 0.7256 0.0000 0 0 0 0.0000 0 0.00
BGC0000001_abyW_24 0.0000 252 0.7381 0.0000 0 0 0 0.0000 0 0.00
Etc.

&

L1.fastq_BGC_metsp.txt
s__Lactobacillus_phage_Sha1 10239|||28883|10699||947981 0.744736534407015
s__Ateline_gammaherpesvirus_3 10239|||548681|10292|10379|85618 0.7419191692604009
s__Streptococcus_sp_HMSC069D09

**Comment by danielchang2002** [comment]
It looks like there are few species detected by metaphlan and the BGCs are not covered by your metagenomic sample (at least for the output you've pasted), so it makes sense that no BGCs are detected. The final output contains information about the predicted biosynthetic gene clusters (i.e., MIBiG BGC IDs), SMs, BGC classes, and source species.
